name: "zenwealth"
services:
  backend:
    container_name: Backend
    image: zenwealth-api:latest
    build:
      context: ./Server
      dockerfile: Dockerfile
#    ports:
#      - "5133:8080"

  frontend:
    container_name: Frontend
    image: zenwealth-spa:latest
    build:
      context: ./Client
      dockerfile: Dockerfile
    depends_on:
      - backend
#    ports:
#      - "3000:80"