name: "zenwealth"
services:
  backend:
    container_name: Backend
    image: zenwealth-api:latest
    build:
      context: ./Server
      dockerfile: Dockerfile

  frontend:
    container_name: Frontend
    image: zenwealth-spa:latest
    build:
      context: ./Client
      dockerfile: Dockerfile
    depends_on:
      - backend